# Generated by Django 4.1 on 2023-01-27 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='PaymentChannel',
        ),
        migrations.RemoveField(
            model_name='user',
            name='accept_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cashbalance',
        ),
    ]
